export type Article={id:string;title:string;terms:string[];answer:string;source:{title:string;url:string};checked:string};
export const articles:Article[]=[
 {id:'cramps',title:'Understanding period cramps',terms:['cramp','pain','ache'],answer:'Warmth, such as a wrapped hot-water bottle, and gentle movement may ease cramps. Pain that is severe, worse than usual or stopping daily activities deserves medical advice. This app does not prescribe medicines or diagnose the cause.',source:{title:'NHS: period pain',url:'https://www.nhs.uk/symptoms/period-pain/'},checked:'2026-09-26'},
 {id:'heavy',title:'When bleeding feels too heavy',terms:['heavy','bleed','blood','clot'],answer:'Needing very frequent product changes, bleeding through clothing, or bleeding for more than seven days can indicate heavy periods. Arrange a clinical assessment if this affects you. Fainting, severe weakness or becoming very unwell needs urgent care.',source:{title:'NHS: heavy periods',url:'https://www.nhs.uk/conditions/heavy-periods/'},checked:'2026-09-26'},
 {id:'late',title:'Late, missed or changing periods',terms:['late','miss','irregular','pregnan','cycle'],answer:'A missed period has many possible causes, including pregnancy, stress, breastfeeding and hormonal contraception. A tracker cannot determine the cause or confirm pregnancy. Seek medical advice about persistent changes or three missed periods. Possible pregnancy with pain or bleeding needs prompt assessment.',source:{title:'NHS: missed or late periods',url:'https://www.nhs.uk/symptoms/missed-or-late-periods/'},checked:'2026-09-26'},
 {id:'hygiene',title:'Practical menstrual hygiene',terms:['hygiene','pad','tampon','cup','clean','wash','product'],answer:'Wash your hands before and after changing a menstrual product. Change pads every few hours, sooner with heavy flow, and follow the product instructions. Wrap disposable products and use a bin rather than flushing them. Follow washing instructions for reusable products.',source:{title:'CDC: menstrual hygiene',url:'https://www.cdc.gov/hygiene/about/menstrual-hygiene.html'},checked:'2026-09-26'},
 {id:'first',title:'Your first period',terms:['first','puberty','school','daughter'],answer:'A first period is part of puberty. Pads, period underwear and other period products are available; a trusted adult or health professional can help you choose and learn to use them. A clinician can help if periods have not begun by age 15. You deserve support without shame.',source:{title:'NHS: periods and puberty',url:'https://www.nhs.uk/conditions/periods/'},checked:'2026-09-26'},
 {id:'pregnancy',title:'Pain or bleeding when pregnancy is possible',terms:['shoulder','one-sided','ectopic','pregnant'],answer:'Pain or bleeding when pregnancy is possible needs prompt medical assessment, even without a positive test. Sudden intense abdominal pain, fainting, or shoulder-tip pain can require emergency care. Do not use this app to rule out an emergency.',source:{title:'NHS: ectopic pregnancy symptoms',url:'https://www.nhs.uk/conditions/ectopic-pregnancy/symptoms/'},checked:'2026-09-26'}
];
export function answerQuestion(question:string) {
 const q=question.trim().toLowerCase();
 // Conservative caution only, NOT a validated free-text triage classifier.
 const caution=/faint|passed out|breath|chest pain|severe|unbearable|shoulder|sudden|soaking/.test(q);
 const results=articles.map(article=>({article,score:article.terms.reduce((score,word)=>score+(q.includes(word)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,2).map(x=>x.article);
 return {mode:'curated-education' as const,caution,articles:results,answer:results.length?results.map(a=>a.answer).join('\n\n'):'This English-language reference library covers cramps, bleeding, late periods, hygiene and first periods. It cannot assess personal symptoms or answer every question. Please speak with a qualified clinician for individual medical advice.'};
}
