import type { IlaraLanguage } from "./languages";
const COPY = {
  home: ["Home", "Ilé", "Gida", "Ụlọ"],
  track: ["Track", "Tọpa", "Bibiyar", "Sochie"],
  ask: ["Ask", "Béèrè", "Tambaya", "Jụọ"],
  history: ["History", "Àwọn àkọsílẹ̀", "Tarihi", "Ndekọ"],
  help: ["Help", "Ìrànlọ́wọ́", "Taimako", "Enyemaka"],
  settings: [
    "Account & settings",
    "Àkọọ́lẹ̀ àti ètò",
    "Asusu da saituna",
    "Akaụntụ na ntọala",
  ],
  language: ["Language", "Èdè", "Harshe", "Asụsụ"],
  skip: [
    "Skip to main content",
    "Lọ sí àkóónú pàtàkì",
    "Tsallaka zuwa babban bayani",
    "Gaa n’ozi bụ isi",
  ],
  periods: ["Periods", "Oṣù", "Al’ada", "Ịhụ nsọ"],
  fertility: [
    "Fertility information",
    "Ìmọ̀ nípa oyún",
    "Bayani kan haihuwa",
    "Ozi ịtụrụ ime",
  ],
  pregnancy: ["Pregnancy records", "Àkọsílẹ̀ oyún", "Bayanan ciki", "Ndekọ ime"],
  conception: [
    "Trying to conceive",
    "Gbígbìyànjú láti lóyún",
    "Ƙoƙarin samun ciki",
    "Ịgbalị ịtụrụ ime",
  ],
  baby: [
    "Baby care records",
    "Àkọsílẹ̀ ọmọ",
    "Bayanan kula da jariri",
    "Ndekọ nwa",
  ],
  growth: [
    "Growth records",
    "Àkọsílẹ̀ ìdàgbàsókè",
    "Bayanan girma",
    "Ndekọ uto",
  ],
  onDevice: [
    "On this device",
    "Lórí ẹ̀rọ yìí",
    "A wannan na’urar",
    "Na ngwaọrụ a",
  ],
  recordOnly: ["Records only", "Àkọsílẹ̀ nìkan", "Bayanan kawai", "Ndekọ naanị"],
  educationOnly: ["Information", "Ìmọ̀", "Bayani", "Ozi"],
  logPeriod: ["Log a period", "Kọ oṣù sílẹ̀", "Rubuta al’ada", "Dekọọ ịhụ nsọ"],
  viewTracker: [
    "View updated tracker",
    "Wo àkọsílẹ̀ tuntun",
    "Duba sabon bayani",
    "Lee ndekọ emelitere",
  ],
  viewRecord: ["View record", "Wo àkọsílẹ̀", "Duba bayani", "Lee ndekọ"],
  noRecords: [
    "No records yet",
    "Kò tíì sí àkọsílẹ̀",
    "Babu bayanai tukuna",
    "Enweghị ndekọ ugbu a",
  ],
  purpose: [
    "Track your periods and ask menstrual health questions in your language.",
    "Tọpa oṣù rẹ, kí o sì béèrè ìbéèrè ìlera oṣù ní èdè rẹ.",
    "Ki bibiyi al’adarki kuma ki tambayi lafiyar al’ada a harshenki.",
    "Sochie ịhụ nsọ gị ma jụọ ajụjụ ahụike n’asụsụ gị.",
  ],
  focus: [
    "What would you like help with?",
    "Kí ni o fẹ́ ìrànlọ́wọ́ pẹ̀lú?",
    "Me kike son taimako a kai?",
    "Kedu ihe ị chọrọ enyemaka na ya?",
  ],
  changeFocus: [
    "Change focus",
    "Yí ohun tí o ń tọpa padà",
    "Sauya abin da ake bibiyarsa",
    "Gbanwee ihe ị na-elekwasị anya",
  ],
  general: [
    "General menstrual questions",
    "Ìbéèrè nípa oṣù",
    "Tambayoyin al’ada",
    "Ajụjụ gbasara ịhụ nsọ",
  ],
  chooseLater: [
    "Choose later",
    "Yan nígbà míì",
    "Zaɓa daga baya",
    "Họrọ ma emechaa",
  ],
  continue: ["Continue", "Tẹ̀síwájú", "Ci gaba", "Gaa n’ihu"],
  back: ["Back", "Padà", "Komawa", "Laghachi"],
  change: ["Change", "Yí padà", "Sauya", "Gbanwee"],
  cancel: ["Cancel", "Fagilé", "Soke", "Kagbuo"],
  keep: ["Keep record", "Pa àkọsílẹ̀ mọ́", "Ajiye bayani", "Debe ndekọ"],
  delete: ["Delete", "Pa rẹ́", "Goge", "Hichapụ"],
  edit: ["Edit record", "Ṣàtúnṣe àkọsílẹ̀", "Gyara bayani", "Dezie ndekọ"],
  dates: ["Dates", "Ọjọ́", "Ranaku", "Ụbọchị"],
  details: ["Details", "Àlàyé", "Cikakkun bayanai", "Nkọwa"],
  review: [
    "Review before saving",
    "Ṣàyẹ̀wò kí o tó fi pamọ́",
    "Duba kafin ajiyewa",
    "Nyochaa tupu ịchekwa",
  ],
  startDate: [
    "Period start date",
    "Ọjọ́ tí oṣù bẹ̀rẹ̀",
    "Ranar fara al’ada",
    "Ụbọchị ịhụ nsọ malitere",
  ],
  endDate: [
    "Period end date (optional)",
    "Ọjọ́ tí oṣù parí (kò pọndandan)",
    "Ranar ƙare al’ada (na zaɓi)",
    "Ụbọchị ịhụ nsọ kwụsịrị (nhọrọ)",
  ],
  ongoing: [
    "Still ongoing",
    "Ó ṣì ń bá a lọ",
    "Har yanzu tana ci gaba",
    "Ọ ka na-aga n’ihu",
  ],
  unknownEnd: [
    "I do not know the end date",
    "Mi ò mọ ọjọ́ tí ó parí",
    "Ban san ranar ƙarewa ba",
    "Amaghị m ụbọchị ọ kwụsịrị",
  ],
  flow: [
    "Flow (optional)",
    "Ẹ̀jẹ̀ (kò pọndandan)",
    "Jini (na zaɓi)",
    "Ọbara (nhọrọ)",
  ],
  spotting: ["Spotting", "Ẹ̀jẹ̀ díẹ̀díẹ̀", "Ɗigon jini", "Obere ntụpọ ọbara"],
  light: ["Light", "Díẹ̀", "Kaɗan", "Obere"],
  medium: ["Medium", "Déédéé", "Matsakaici", "Etiti"],
  heavy: ["Heavy", "Púpọ̀", "Mai yawa", "Ọtụtụ"],
  pain: [
    "Pain (0 = none, 10 = most severe)",
    "Ìrora (0 = kò sí, 10 = tó lágbára jù)",
    "Ciwo (0 = babu, 10 = mafi tsanani)",
    "Mgbu (0 = enweghị, 10 = kacha njọ)",
  ],
  notSure: ["Not sure", "Mi ò dájú", "Ban tabbatar ba", "Ejighị m n’aka"],
  notProvided: ["Not provided", "A kò pèsè", "Ba a bayar ba", "Enyeghị"],
  symptoms: [
    "Other symptoms (optional)",
    "Àwọn àmì mìíràn (kò pọndandan)",
    "Sauran alamomi (na zaɓi)",
    "Ihe mgbaàmà ọzọ (nhọrọ)",
  ],
  tired: ["Tired", "Ìrẹ̀wẹ̀sì", "Gajiya", "Ike ọgwụgwụ"],
  headache: ["Headache", "Ẹ̀fọ́rí", "Ciwon kai", "Isi ọwụwa"],
  cramps: ["Cramps", "Ìrora ikùn", "Ciwon ciki", "Mgbu afọ"],
  savePeriod: ["Save period", "Fi oṣù pamọ́", "Ajiye al’ada", "Chekwaa ịhụ nsọ"],
  saveChanges: [
    "Save changes",
    "Fi àtúnṣe pamọ́",
    "Ajiye gyare-gyare",
    "Chekwaa mgbanwe",
  ],
  saving: ["Saving…", "Ń fi pamọ́…", "Ana ajiyewa…", "Na-echekwa…"],
  periodSaved: [
    "Period saved on this device",
    "A ti fi oṣù pamọ́ lórí ẹ̀rọ yìí",
    "An ajiye al’ada a wannan na’urar",
    "Echekwara ịhụ nsọ na ngwaọrụ a",
  ],
  notSaved: [
    "This record has not been saved. Try again.",
    "A kò tíì fi àkọsílẹ̀ yìí pamọ́. Gbìyànjú lẹ́ẹ̀kan sí i.",
    "Ba a ajiye wannan bayani ba. Sake gwadawa.",
    "Echekwaghị ndekọ a. Gbalịa ọzọ.",
  ],
  calendar: ["Calendar", "Kàlẹ́ńdà", "Kalanda", "Kalenda"],
  list: ["List", "Àtòjọ", "Jeri", "Ndepụta"],
  today: ["Today", "Òní", "Yau", "Taa"],
  previousMonth: [
    "Previous month",
    "Oṣù tó ṣáájú",
    "Watan da ya gabata",
    "Ọnwa gara aga",
  ],
  nextMonth: ["Next month", "Oṣù tó ń bọ̀", "Wata na gaba", "Ọnwa na-abịa"],
  recorded: [
    "Recorded period",
    "Oṣù tí a kọ sílẹ̀",
    "Al’ada da aka rubuta",
    "Ịhụ nsọ e dere",
  ],
  selected: ["Selected", "Tí a yàn", "An zaɓa", "Ahọpụtara"],
  noPeriod: [
    "No period recorded for this day.",
    "A kò kọ oṣù sílẹ̀ fún ọjọ́ yìí.",
    "Ba a rubuta al’ada a wannan rana ba.",
    "Enweghị ịhụ nsọ e dere ụbọchị a.",
  ],
  signIn: ["Sign in", "Wọlé", "Shiga", "Banye"],
  signOut: ["Sign out", "Jáde", "Fita", "Pụọ"],
  signUp: ["Create account", "Ṣẹ̀dá àkọọ́lẹ̀", "Ƙirƙiri asusu", "Mepụta akaụntụ"],
  phone: ["Phone number", "Nọ́mbà fóònù", "Lambar waya", "Nọmba ekwentị"],
  password: ["Password", "Ọ̀rọ̀ aṣínà", "Kalmar sirri", "Okwuntughe"],
  confirmPassword: [
    "Confirm password",
    "Jẹ́rìí ọ̀rọ̀ aṣínà",
    "Tabbatar da kalmar sirri",
    "Kwenye okwuntughe",
  ],
  showPassword: [
    "Show password",
    "Fi ọ̀rọ̀ aṣínà hàn",
    "Nuna kalmar sirri",
    "Gosi okwuntughe",
  ],
  hidePassword: [
    "Hide password",
    "Fi ọ̀rọ̀ aṣínà pamọ́",
    "Ɓoye kalmar sirri",
    "Zoo okwuntughe",
  ],
  recordQuestion: [
    "Record a question",
    "Gba ìbéèrè sílẹ̀",
    "Yi rikodin tambaya",
    "Dekọọ ajụjụ",
  ],
  confirmAsk: [
    "Confirm and ask",
    "Jẹ́rìí kí o sì béèrè",
    "Tabbatar sannan tambaya",
    "Kwenye ma jụọ",
  ],
  heard: [
    "Check what we heard",
    "Ṣàyẹ̀wò ohun tí a gbọ́",
    "Duba abin da muka ji",
    "Nyochaa ihe anyị nụrụ",
  ],
  recording: ["Recording…", "Ń gba ohùn sílẹ̀…", "Ana rikodi…", "Na-edekọ…"],
  checkingAudio: [
    "Checking what you said…",
    "Ń ṣàyẹ̀wò ohun tí o sọ…",
    "Ana duba abin da kika ce…",
    "Na-enyocha ihe i kwuru…",
  ],
  preparing: [
    "Preparing your answer…",
    "Ń pèsè ìdáhùn rẹ…",
    "Ana shirya amsarki…",
    "Na-akwadebe azịza gị…",
  ],
  listen: ["Listen", "Gbọ́", "Saurara", "Gee ntị"],
  pause: ["Pause", "Dá dúró díẹ̀", "Dakata", "Kwụsịtụ"],
  resume: ["Resume", "Tẹ̀síwájú", "Ci gaba", "Gaa n’ihu"],
  stop: ["Stop", "Dá dúró", "Tsaya", "Kwụsị"],
  discard: ["Discard", "Kọ̀ ọ́ sílẹ̀", "Watsar", "Tụfuo"],
  rerecord: [
    "Record again",
    "Gba ohùn sílẹ̀ lẹ́ẹ̀kan sí i",
    "Sake rikodi",
    "Dekọọ ọzọ",
  ],
  newConversation: [
    "Start a new conversation",
    "Bẹ̀rẹ̀ ìjíròrò tuntun",
    "Fara sabuwar tattaunawa",
    "Malite mkparịta ụka ọhụrụ",
  ],
  savedConversations: [
    "Open saved conversations",
    "Ṣí ìjíròrò tí a fi pamọ́",
    "Buɗe tattaunawar da aka ajiye",
    "Mepee mkparịta ụka echekwara",
  ],
  urgentHelp: [
    "Need urgent help?",
    "Ṣé o nílò ìrànlọ́wọ́ kíákíá?",
    "Kina bukatar taimakon gaggawa?",
    "Ị chọrọ enyemaka ngwa ngwa?",
  ],
  basicGuidance: [
    "Basic guidance",
    "Ìtọ́sọ́nà ìpilẹ̀",
    "Bayani na asali",
    "Nduzi bụ isi",
  ],
  sources: [
    "Sources and details",
    "Orísun àti àlàyé",
    "Tushe da cikakken bayani",
    "Isi mmalite na nkọwa",
  ],
  retry: ["Try again", "Gbìyànjú lẹ́ẹ̀kan sí i", "Sake gwadawa", "Gbalịa ọzọ"],
  loading: [
    "Opening saved records…",
    "Ń ṣí àkọsílẹ̀ tí a fi pamọ́…",
    "Ana buɗe bayanan da aka ajiye…",
    "Na-emepe ndekọ echekwara…",
  ],
  offline: [
    "You are offline. Local logging works; new voice questions need internet.",
    "Kò sí ìkànnì. O lè kọ àkọsílẹ̀; ìbéèrè ohùn tuntun nílò ìkànnì.",
    "Babu intanet. Ajiyar bayanai na aiki; sababbin tambayoyin murya na bukatar intanet.",
    "Ị nọ na-enweghị ịntanetị. Ịdekọ na-arụ ọrụ; ajụjụ olu ọhụrụ chọrọ ịntanetị.",
  ],
  privacy: [
    "Privacy and saved information",
    "Àṣírí àti ìmọ̀ tí a fi pamọ́",
    "Sirri da bayanan da aka ajiye",
    "Nzuzo na ozi echekwara",
  ],
  sharedDevice: [
    "Shared device",
    "Ẹ̀rọ tí a jọ ń lò",
    "Na’urar da ake rabawa",
    "Ngwaọrụ a na-ekekọrịta",
  ],
  keepConversations: [
    "Keep conversations on this device",
    "Pa ìjíròrò mọ́ lórí ẹ̀rọ yìí",
    "Ajiye tattaunawa a wannan na’urar",
    "Debe mkparịta ụka na ngwaọrụ a",
  ],
  keepAudio: [
    "Keep recordings on this device",
    "Pa ohùn mọ́ lórí ẹ̀rọ yìí",
    "Ajiye rikodi a wannan na’urar",
    "Debe ndekọ olu na ngwaọrụ a",
  ],
  externalAI: [
    "Allow external AI explanations",
    "Gba àlàyé AI láti iṣẹ́ òde",
    "Yarda da bayanin AI na waje",
    "Kwe ka AI dị n’èzí kọwaa",
  ],
  hidePreviews: [
    "Hide sensitive previews",
    "Fi àkọ́kọ́ àlàyé ìkọ̀kọ̀ pamọ́",
    "Ɓoye bayanan sirri",
    "Zoo ozi nzuzo",
  ],
  lowData: [
    "Use low-data mode",
    "Lo ìkànnì díẹ̀",
    "Yi amfani da ƙarancin data",
    "Jiri obere data",
  ],
  export: [
    "Export selected records",
    "Gbé àkọsílẹ̀ tí a yàn jáde",
    "Fitar da bayanan da aka zaɓa",
    "Bupụ ndekọ ahọpụtara",
  ],
  restore: [
    "Restore from a file",
    "Dá àkọsílẹ̀ padà láti fáìlì",
    "Maido daga fayil",
    "Weghachite site na faịlụ",
  ],
  all: ["All", "Gbogbo", "Duka", "Niile"],
  conversations: ["Conversations", "Ìjíròrò", "Tattaunawa", "Mkparịta ụka"],
  feedback: [
    "Share feedback",
    "Pín èrò rẹ",
    "Bayar da ra’ayi",
    "Kekọrịta echiche",
  ],
  englishNotice: [
    "This information is available in English. Native-language review is pending.",
    "Ìmọ̀ yìí wà ní èdè Gẹ̀ẹ́sì. Àyẹ̀wò èdè abinibi ṣì ń dúró.",
    "Wannan bayani yana cikin Turanci. Ana jiran duba harshen gida.",
    "Ozi a dị n’asụsụ Bekee. A ka na-echere nyocha asụsụ obodo.",
  ],
} as const;
export type CopyKey = keyof typeof COPY;
export function copy(language: IlaraLanguage, key: CopyKey) {
  return COPY[key][
    language === "yo" ? 1 : language === "ha" ? 2 : language === "ig" ? 3 : 0
  ];
}
