"use client";
import { useLanguage } from "./use-language";
import type { IlaraLanguage } from "./languages";
// A single interface catalogue. Clinical answers keep their existing reviewed localization.
const rows = {
  listenReply: [
    "Listen to reply",
    "Gbọ́ ìdáhùn",
    "Saurari amsa",
    "Gee nzaghachi",
  ],
  deviceVoice: [
    "Device voice · not saved audio",
    "Ohùn ẹ̀rọ · kì í ṣe ohùn tí a tọ́jú",
    "Muryar na’ura · ba rikodin da aka adana ba",
    "Olu ngwaọrụ · abụghị ọdịyo echekwara",
  ],
  voiceUnavailable: [
    "Device voice unavailable. Read the reply or request saved audio.",
    "Ohùn ẹ̀rọ kò wà. Ka ìdáhùn tàbí béèrè ohùn tí a tọ́jú.",
    "Muryar na’ura ba ta samuwa. Karanta amsa ko nemi rikodin da aka adana.",
    "Olu ngwaọrụ adịghị. Gụọ nzaghachi ma ọ bụ rịọ ọdịyo echekwara.",
  ],
  cycle: ["Cycle", "Òṣù", "Zagaye", "Oge nsọ"],
  chat: ["Chat", "Ìjíròrò", "Tattaunawa", "Mkparịta ụka"],
  logs: ["Logs", "Àkọsílẹ̀", "Bayanan", "Ndekọ"],
  help: ["Help", "Ìrànlọ́wọ́", "Taimako", "Enyemaka"],
  space: ["Your space", "Ààyè rẹ", "Wurinki", "Ebe gị"],
  privacyLanguage: [
    "Privacy & language",
    "Àṣírí àti èdè",
    "Sirri da harshe",
    "Nzuzo na asụsụ",
  ],
  dailySpace: [
    "YOUR DAILY SPACE",
    "ÀÀYÈ OJOOJÚMỌ́ RẸ",
    "WURINKI NA KULLUM",
    "EBE GỊ KWA ỤBỌCHỊ",
  ],
  close: ["Close", "Pa á dé", "Rufe", "Mechie"],
  back: ["Back", "Padà", "Koma", "Laghachi"],
  cancel: ["Cancel", "Fagilé", "Soke", "Kagbuo"],
  save: ["Save log", "Fi àkọsílẹ̀ pamọ́", "Ajiye bayanai", "Chekwaa ndekọ"],
  edit: ["Edit log", "Ṣàtúnṣe àkọsílẹ̀", "Gyara bayanai", "Dezie ndekọ"],
  delete: ["Delete", "Pa rẹ́", "Goge", "Hichapụ"],
  export: [
    "Export records",
    "Gba àkọsílẹ̀ jáde",
    "Fitar da bayanai",
    "Budata ndekọ",
  ],
  today: ["Today", "Òní", "Yau", "Taa"],
  myCycle: ["My cycle", "Òṣù mi", "Zagayena", "Oge nsọ m"],
  logToday: ["Log today", "Ṣàkọsílẹ̀ òní", "Rubuta na yau", "Dekọọ taa"],
  ask: ["Ask", "Béèrè", "Tambaya", "Jụọ"],
  periodLogged: [
    "PERIOD LOGGED",
    "A TI ṢÀKỌSÍLẸ̀ ÒṢÙ",
    "AN RUBUTA HAILA",
    "EDEKỌỌLA OGE NSỌ",
  ],
  day: ["Day", "Ọjọ́", "Rana", "Ụbọchị"],
  nextPeriod: ["Next period", "Òṣù tó kàn", "Haila mai zuwa", "Oge nsọ ọzọ"],
  estimate: ["Estimate", "Àfojúsùn", "Hasashe", "Atụmatụ"],
  stillLearning: [
    "Still learning",
    "A ṣì ń kọ́",
    "Ana ƙara fahimta",
    "A ka na-amụta",
  ],
  learningHint: [
    "Add at least two period starts for an estimate.",
    "Fi ọjọ́ ìbẹ̀rẹ̀ òṣù méjì kún un fún àfojúsùn.",
    "Ƙara farkon haila biyu domin hasashe.",
    "Tinye ụbọchị mmalite oge nsọ abụọ maka atụmatụ.",
  ],
  emptyCycle: [
    "Your rhythm starts here.",
    "Ìlù ara rẹ bẹ̀rẹ̀ níbí.",
    "Zagayenki yana farawa nan.",
    "Usoro ahụ gị na-amalite ebe a.",
  ],
  firstLog: [
    "Log your first period",
    "Ṣàkọsílẹ̀ òṣù àkọ́kọ́ rẹ",
    "Rubuta hailarki ta farko",
    "Dekọọ oge nsọ mbụ gị",
  ],
  noLogs: [
    "No logs yet",
    "Kò sí àkọsílẹ̀ síbẹ̀",
    "Babu bayanai tukuna",
    "Enweghị ndekọ ugbu a",
  ],
  noLog: [
    "No log for this day",
    "Kò sí àkọsílẹ̀ fún ọjọ́ yìí",
    "Babu bayanai na wannan rana",
    "Enweghị ndekọ maka ụbọchị a",
  ],
  logged: ["Logged", "Àkọsílẹ̀", "An rubuta", "Edekọọla"],
  selected: ["Selected", "Tí a yàn", "An zaɓa", "Ahọpụtara"],
  previousMonth: [
    "Previous month",
    "Oṣù tó kọjá",
    "Watan baya",
    "Ọnwa gara aga",
  ],
  nextMonth: ["Next month", "Oṣù tó kàn", "Wata mai zuwa", "Ọnwa ọzọ"],
  logPeriod: ["Log a period", "Ṣàkọsílẹ̀ òṣù", "Rubuta haila", "Dekọọ oge nsọ"],
  periodDates: ["Period dates", "Ọjọ́ òṣù", "Kwanakin haila", "Ụbọchị oge nsọ"],
  started: ["Started", "Bẹ̀rẹ̀", "An fara", "Malitere"],
  ended: ["Ended", "Parí", "An ƙare", "Kwụsịrị"],
  ongoing: ["Ongoing", "Ó ṣì ń lọ", "Ana ciki", "Ọ ka na-aga"],
  flow: ["Flow", "Ẹ̀jẹ̀", "Jinin haila", "Ọbara"],
  spotting: ["Spotting", "Ẹ̀jẹ̀ díẹ̀díẹ̀", "Ɗigon jini", "Ntụpọ ọbara"],
  light: ["Light", "Díẹ̀", "Kaɗan", "Obere"],
  medium: ["Medium", "Àárín", "Matsakaici", "Etiti"],
  heavy: ["Heavy", "Púpọ̀", "Mai yawa", "Ọtụtụ"],
  pain: ["Pain", "Ìrora", "Ciwo", "Mgbu"],
  none: ["None", "Kò sí", "Babu", "Enweghị"],
  worst: ["Worst", "Tó pọ̀ jù", "Mafi tsanani", "Kasị njọ"],
  symptoms: ["Symptoms", "Àwọn àmì", "Alamomi", "Mgbaàmà"],
  cramps: ["Cramps", "Ìrora inú", "Murɗawar ciki", "Mgbu afọ"],
  tired: ["Tired", "Àárẹ̀", "Gajiya", "Ike ọgwụgwụ"],
  tender: ["Tender breasts", "Ọmú tó ń dun", "Ciwon nono", "Mgbu ara"],
  headache: ["Headache", "Ẹ̀fọ́rí", "Ciwon kai", "Isi ọwụwa"],
  more: ["More", "Sí i", "Ƙari", "Ọzọ"],
  addNote: [
    "Add a note",
    "Fi àkọsílẹ̀ kún un",
    "Ƙara bayanin kula",
    "Tinye ndetu",
  ],
  note: [
    "Note (optional)",
    "Àkọsílẹ̀ (bí o bá fẹ́)",
    "Bayanin kula (na zaɓi)",
    "Ndetu (ọ bụrụ na ịchọrọ)",
  ],
  savedBrowser: [
    "Saved in this browser",
    "A fi pamọ́ sínú aṣàwákiri yìí",
    "An ajiye a wannan burauza",
    "Echekwara na nchọgharị a",
  ],
  logSaved: [
    "Log saved",
    "A fi àkọsílẹ̀ pamọ́",
    "An ajiye bayanai",
    "Echekwara ndekọ",
  ],
  periods: ["Periods", "Òṣù", "Haila", "Oge nsọ"],
  notes: ["Notes", "Àkọsílẹ̀", "Bayanan kula", "Ndetu"],
  myLogs: ["My logs", "Àkọsílẹ̀ mi", "Bayanana", "Ndekọ m"],
  hereForYou: [
    "Here for you",
    "A wà fún ọ",
    "Muna nan domin ki",
    "Anyị nọ maka gị",
  ],
  chooseNeed: [
    "Choose what you need.",
    "Yan ohun tí o nílò.",
    "Zaɓi abin da kike buƙata.",
    "Họrọ ihe ị chọrọ.",
  ],
  lowData: [
    "Low-data voice",
    "Ohùn pẹ̀lú dátà díẹ̀",
    "Murya mai ƙarancin data",
    "Olu na obere data",
  ],
  lowDataHint: [
    "A simpler way to speak",
    "Ọ̀nà tó rọrùn láti sọ̀rọ̀",
    "Hanya mafi sauƙi ta magana",
    "Ụzọ dị mfe isi kwuo okwu",
  ],
  care: [
    "Care guidance",
    "Ìtọ́sọ́nà ìtọ́jú",
    "Shawarwarin kulawa",
    "Nduzi nlekọta",
  ],
  careHint: [
    "When to seek more support",
    "Ìgbà láti wá ìrànlọ́wọ́ sí i",
    "Lokacin neman ƙarin taimako",
    "Mgbe ị ga-achọ enyemaka ọzọ",
  ],
  yourChoices: [
    "Your records, your choices",
    "Àkọsílẹ̀ rẹ, yíyan rẹ",
    "Bayananki, zaɓinki",
    "Ndekọ gị, nhọrọ gị",
  ],
  feedback: [
    "Share feedback",
    "Fún wa ní èsì",
    "Bayar da ra'ayi",
    "Nye nzaghachi",
  ],
  feedbackHint: [
    "Help shape ÌleraHer",
    "Ràn ÌleraHer lọ́wọ́",
    "Taimaka inganta ÌleraHer",
    "Nyere aka imezi ÌleraHer",
  ],
  phone: [
    "Phone support",
    "Ìrànlọ́wọ́ tẹlifóònù",
    "Taimakon waya",
    "Enyemaka ekwentị",
  ],
  comingSoon: ["Coming soon", "Ó ń bọ̀ láìpẹ́", "Yana tafe", "Ọ na-abịa"],
  verifiedNumber: [
    "A verified number will appear here.",
    "Nọ́mbà tí a ti jẹ́rìí sí yóò hàn níbí.",
    "Lambar da aka tabbatar za ta bayyana nan.",
    "Nọmba akwadoro ga-apụta ebe a.",
  ],
  healthInfo: [
    "Health information · not a diagnosis",
    "Àlàyé ìlera · kì í ṣe àyẹ̀wò àìsàn",
    "Bayanin lafiya · ba ganewar cuta ba",
    "Ozi ahụike · abụghị nchọpụta ọrịa",
  ],
  language: ["Language", "Èdè", "Harshe", "Asụsụ"],
  chooseLanguage: [
    "Choose your language",
    "Yan èdè rẹ",
    "Zaɓi harshenki",
    "Họrọ asụsụ gị",
  ],
  getStarted: ["Get started", "Bẹ̀rẹ̀", "Fara", "Malite"],
  explore: ["Explore first", "Ṣàyẹ̀wò kọ́kọ́", "Duba tukuna", "Lelee mbụ"],
  yourRhythm: [
    "Your body, your rhythm.",
    "Ara rẹ, ìlù rẹ.",
    "Jikinki, zagayenki.",
    "Ahụ gị, usoro gị.",
  ],
  trackTalk: [
    "Track. Talk. Feel supported.",
    "Ṣàkọsílẹ̀. Sọ̀rọ̀. Gba ìrànlọ́wọ́.",
    "Bi diddigi. Yi magana. Samu taimako.",
    "Dekọọ. Kwuo okwu. Nweta nkwado.",
  ],
  aiGuide: [
    "AI health guide",
    "Olùtọ́sọ́nà ìlera AI",
    "Jagoran lafiya na AI",
    "Onye nduzi ahụike AI",
  ],
  historyDevice: [
    "History on this device",
    "Ìtàn lórí ẹ̀rọ yìí",
    "Tarihi a wannan na'ura",
    "Akụkọ na ngwaọrụ a",
  ],
  greeting: [
    "Hi, I’m here to listen. What would you like to ask?",
    "Ẹ káàbọ̀, mo wà níbí láti fetí sí ọ. Kí lo fẹ́ béèrè?",
    "Sannu, ina nan don saurare. Me kike son tambaya?",
    "Ndewo, anọ m ebe a ige gị ntị. Gịnị ka ị chọrọ ịjụ?",
  ],
  wellbeing: ["Wellbeing", "Ìlera", "Jin daɗi", "Ahụike"],
  myPeriod: ["My period", "Òṣù mi", "Hailata", "Oge nsọ m"],
  message: ["Message…", "Ọ̀rọ̀…", "Saƙo…", "Ozi…"],
  typeInstead: [
    "Type instead",
    "Kọ̀wé dípò rẹ̀",
    "Rubuta maimakon haka",
    "Dee kama ikwu okwu",
  ],
  record: [
    "Tap to record",
    "Tẹ̀ láti gbà ohùn",
    "Taɓa don yin rikodi",
    "Pịa ka ị dekọọ",
  ],
  recordAgain: [
    "Record again",
    "Gba ohùn lẹ́ẹ̀kan sí i",
    "Sake yin rikodi",
    "Dekọọ ọzọ",
  ],
  upTo60: [
    "Up to 60 seconds",
    "Títí dé ìṣẹ́jú-àáyá 60",
    "Har daƙiƙa 60",
    "Ruo sekọnd 60",
  ],
  recording: ["Recording…", "Ó ń gba ohùn…", "Ana rikodi…", "A na-edekọ…"],
  paused: ["Paused", "A dákẹ́", "An dakata", "Akwụsịtụrụ"],
  pause: ["Pause", "Dákẹ́", "Dakatar", "Kwụsịtụ"],
  resume: ["Resume", "Tẹ̀síwájú", "Ci gaba", "Gaa n'ihu"],
  review: ["Review", "Ṣàyẹ̀wò", "Duba", "Nyochaa"],
  discard: [
    "Discard draft",
    "Pa àkọ́kọ́ rẹ́",
    "Watsar da daftari",
    "Tụfuo ihe e dere",
  ],
  yourWords: [
    "Your voice. Your words.",
    "Ohùn rẹ. Ọ̀rọ̀ rẹ.",
    "Muryarki. Kalmominki.",
    "Olu gị. Okwu gị.",
  ],
  reviewHint: [
    "Listen once, then check the words.",
    "Gbọ́ ọ, lẹ́yìn náà ṣàyẹ̀wò ọ̀rọ̀ náà.",
    "Saurara, sannan duba kalmomin.",
    "Gee ntị, lelee okwu ahụ.",
  ],
  transcript: ["Transcript", "Ọ̀rọ̀ ohùn", "Rubutun murya", "Ederede olu"],
  editWords: ["Edit words", "Ṣàtúnṣe ọ̀rọ̀", "Gyara kalmomi", "Dezie okwu"],
  transcribe: [
    "Transcribe recording",
    "Ṣàyẹ̀wò ohùn",
    "Duba rikodi",
    "Nyochaa ndekọ olu",
  ],
  transcribing: [
    "Reading your audio…",
    "A ń ka ohùn rẹ…",
    "Ana karanta muryarki…",
    "A na-agụ olu gị…",
  ],
  send: ["Send message", "Fi ọ̀rọ̀ ránṣẹ́", "Aika saƙo", "Zipu ozi"],
  sending: [
    "Preparing your reply…",
    "A ń pèsè èsì rẹ…",
    "Ana shirya amsa…",
    "A na-akwadebe nzaghachi…",
  ],
  retry: ["Try again", "Gbìyànjú lẹ́ẹ̀kan sí i", "Sake gwadawa", "Gbalịa ọzọ"],
  reply: ["Reply", "Dáhùn", "Amsa", "Zaghachi"],
  readReply: ["Read reply", "Ka èsì", "Karanta amsa", "Gụọ nzaghachi"],
  showTranscript: [
    "Show transcript",
    "Fi ọ̀rọ̀ hàn",
    "Nuna rubutu",
    "Gosi ederede",
  ],
  you: ["You", "Ìwọ", "Ke", "Gị"],
  play: ["Play audio", "Gbọ́ ohùn", "Kunna sauti", "Kpọọ olu"],
  speed: ["Playback speed", "Ìyára ohùn", "Saurin sauti", "Ọsọ olu"],
  seek: ["Audio position", "Ipò ohùn", "Matsayin sauti", "Ebe olu ruru"],
  download: ["Download", "Gba sílẹ̀", "Sauke", "Budata"],
  share: ["Share", "Pín", "Raba", "Kekọrịta"],
  copy: ["Copy words", "Da ọ̀rọ̀ kọ", "Kwafi kalmomi", "Detuo okwu"],
  newConversation: [
    "New conversation",
    "Ìjíròrò tuntun",
    "Sabuwar tattaunawa",
    "Mkparịta ụka ọhụrụ",
  ],
  conversations: [
    "Saved conversations",
    "Ìjíròrò tí a fi pamọ́",
    "Tattaunawar da aka ajiye",
    "Mkparịta ụka echekwara",
  ],
  search: [
    "Search conversations",
    "Wá ìjíròrò",
    "Nemi tattaunawa",
    "Chọọ mkparịta ụka",
  ],
  rename: ["Rename", "Tún orúkọ ṣe", "Sake suna", "Gbanwee aha"],
  saved: [
    "Saved on this device",
    "A fi pamọ́ lórí ẹ̀rọ yìí",
    "An ajiye a wannan na'ura",
    "Echekwara na ngwaọrụ a",
  ],
  unsaved: [
    "Not saved · keep this tab open",
    "A kò fi pamọ́ · má pa ojú ìwé dé",
    "Ba a ajiye ba · kar ki rufe shafin",
    "Echekwaghị · emechila taabụ a",
  ],
  offline: [
    "You’re offline",
    "O kò sí lórí íntánẹ́ẹ̀tì",
    "Babu intanet",
    "Enweghị ịntanetị",
  ],
  offlineHint: [
    "New replies need internet. Your draft won’t send automatically.",
    "Èsì tuntun nílò íntánẹ́ẹ̀tì. A kò ní fi àkọ́kọ́ rẹ ránṣẹ́ fúnra rẹ̀.",
    "Sabbin amsoshi na buƙatar intanet. Ba za a aika daftarin kai tsaye ba.",
    "Nzaghachi ọhụrụ chọrọ ịntanetị. Agaghị ezipu ihe e dere n'onwe ya.",
  ],
  internet: [
    "Internet needed",
    "A nílò íntánẹ́ẹ̀tì",
    "Ana buƙatar intanet",
    "A chọrọ ịntanetị",
  ],
  newReply: ["New reply", "Èsì tuntun", "Sabuwar amsa", "Nzaghachi ọhụrụ"],
  beforeListen: [
    "Before we listen",
    "Kí a tó fetí sí ọ",
    "Kafin mu saurara",
    "Tupu anyị egee ntị",
  ],
  voiceDisclosure: [
    "Your audio goes to a speech service when you choose Transcribe. Check the words before Send shares them with the AI.",
    "Ohùn rẹ lọ sí iṣẹ́ ohùn nígbà tí o tẹ Ṣàyẹ̀wò. Ṣàyẹ̀wò ọ̀rọ̀ kí o tó fi ránṣẹ́ sí AI.",
    "Ana aika sauti ga sabis na murya idan kin taɓa Duba. Duba kalmomi kafin aika wa AI.",
    "A na-eziga olu gị na ọrụ olu mgbe ị pịrị Nyochaa. Lelee okwu tupu iziga ya na AI.",
  ],
  continueRecord: [
    "Continue to record",
    "Tẹ̀síwájú láti gba ohùn",
    "Ci gaba da rikodi",
    "Gaa n'ihu idekọ",
  ],
  textDisclosure: [
    "Your confirmed words and selected conversation are sent for an answer when you tap Send.",
    "Ọ̀rọ̀ tí o fọwọ́ sí àti ìjíròrò tí o yàn lọ fún èsì nígbà tí o tẹ Ránṣẹ́.",
    "Ana aika kalmomin da kika tabbatar da tattaunawar da kika zaɓa idan kin taɓa Aika.",
    "A na-eziga okwu ị kwadoro na mkparịta ụka ị họọrọ mgbe ị pịrị Zipu.",
  ],
  localDisclosure: [
    "Records stay in this browser. Clearing site data removes them. Shared devices may expose them.",
    "Àkọsílẹ̀ wà nínú aṣàwákiri yìí. Pípa dátà ojú ìwé rẹ́ yọ wọn. Ẹ̀rọ àjọpín lè fi wọn hàn.",
    "Bayanai suna cikin wannan burauza. Goge bayanan shafin yana cire su. Na'urar haɗin gwiwa na iya bayyana su.",
    "Ndekọ dị na nchọgharị a. Ihichapụ data saịtị ga-ewepụ ha. Ngwaọrụ a na-ekekọrịta nwere ike igosi ha.",
  ],
  processingDisclosure: [
    "Audio and confirmed text are processed externally by the configured speech and AI services. Account and feedback records are stored on the server.",
    "Iṣẹ́ ohùn àti AI ló ń ṣe ohùn àti ọ̀rọ̀ tí o fọwọ́ sí níta ẹ̀rọ. Àkọsílẹ̀ àkáǹtì àti èsì wà lórí ẹ̀rọ ìpamọ́.",
    "Sabis na murya da AI na sarrafa sauti da rubutu a waje. Bayanan asusu da ra'ayi suna kan uwar garke.",
    "Ọrụ olu na AI na-ahazi olu na ederede akwadoro n'èzí. Ndekọ akaụntụ na nzaghachi dị na sava.",
  ],
  feedbackTitle: [
    "How did it feel?",
    "Báwo ló ṣe rí?",
    "Yaya kika ji?",
    "Kedu ka ọ dị?",
  ],
  comment: [
    "A little more (optional)",
    "Àlàyé díẹ̀ sí i (bí o bá fẹ́)",
    "Ƙarin bayani (na zaɓi)",
    "Ozi ọzọ (ọ bụrụ na ịchọrọ)",
  ],
  problem: ["Problem", "Ìṣòro", "Matsala", "Nsogbu"],
  idea: ["Idea", "Èrò", "Shawara", "Echiche"],
  loved: ["Loved it", "Mo fẹ́ràn rẹ̀", "Na so shi", "Ọ masịrị m"],
  sendFeedback: [
    "Send feedback",
    "Fi èsì ránṣẹ́",
    "Aika ra'ayi",
    "Zipu nzaghachi",
  ],
  received: ["We heard you.", "A ti gbọ́ ọ.", "Mun ji ki.", "Anyị anụla gị."],
  receivedHint: [
    "Thank you for helping ÌleraHer grow.",
    "Ẹ ṣé fún ìrànlọ́wọ́ láti mú ÌleraHer dàgbà.",
    "Na gode da taimakon inganta ÌleraHer.",
    "Daalụ maka inyere ÌleraHer aka ito.",
  ],
  feedbackPrivacy: [
    "Please leave private health details out of feedback.",
    "Má fi àlàyé ìlera àṣírí sínú èsì.",
    "Kar ki saka bayanan lafiyar sirri a ra'ayi.",
    "Etinyela ozi ahụike nzuzo na nzaghachi.",
  ],
  moment: [
    "A moment for you",
    "Àkókò fún ọ",
    "Ɗan lokaci domin ki",
    "Oge maka gị",
  ],
  momentHint: [
    "Questions about your body? Talk in your own language.",
    "Ìbéèrè nípa ara rẹ? Sọ̀rọ̀ ní èdè rẹ.",
    "Tambaya game da jikinki? Yi magana a harshenki.",
    "Ajụjụ banyere ahụ gị? Kwuo okwu n'asụsụ gị.",
  ],
  startChat: [
    "Start a chat",
    "Bẹ̀rẹ̀ ìjíròrò",
    "Fara tattaunawa",
    "Malite mkparịta ụka",
  ],
  welcome: ["Welcome back", "Ẹ káàbọ̀", "Barka da dawowa", "Nnọọ ọzọ"],
  signIn: ["Sign in", "Wọlé", "Shiga", "Banye"],
  signOut: ["Sign out", "Jáde", "Fita", "Pụọ"],
  createAccount: [
    "Create account",
    "Ṣẹ̀dá àkáǹtì",
    "Ƙirƙiri asusu",
    "Mepụta akaụntụ",
  ],
  password: ["Password", "Ọ̀rọ̀ ìwọlé", "Kalmar sirri", "Okwuntughe"],
  phoneNumber: [
    "Phone number",
    "Nọ́mbà tẹlifóònù",
    "Lambar waya",
    "Nọmba ekwentị",
  ],
  confirmPassword: [
    "Confirm password",
    "Jẹ́rìí ọ̀rọ̀ ìwọlé",
    "Tabbatar kalmar sirri",
    "Kwado okwuntughe",
  ],
  loading: [
    "Opening your space…",
    "A ń ṣí ààyè rẹ…",
    "Ana buɗe wurinki…",
    "A na-emepe ebe gị…",
  ],
  saveError: [
    "Could not save. Your draft is still here.",
    "A kò lè fi pamọ́. Àkọ́kọ́ rẹ ṣì wà níbí.",
    "An kasa ajiyewa. Daftarki yana nan.",
    "Enweghị ike ichekwa. Ihe e dere ka dị ebe a.",
  ],
  unsavedChanges: [
    "Leave this form? Your unfinished draft will stay in this tab.",
    "Kúrò ní fọ́ọ̀mù yìí? Àkọ́kọ́ rẹ yóò wà lórí ojú ìwé yìí.",
    "Bar wannan fom? Daftarki za ta kasance a wannan shafin.",
    "Hapụ fọm a? Ihe e dere ga-adị na taabụ a.",
  ],
  validDates: [
    "Choose valid dates, no later than today.",
    "Yan ọjọ́ tó tọ́, tí kò kọjá òní.",
    "Zaɓi kwanaki masu inganci, ba bayan yau ba.",
    "Họrọ ụbọchị ziri ezi, ọ bụghị mgbe taa gasịrị.",
  ],
  overlap: [
    "These dates overlap a saved period. Update that record first.",
    "Ọjọ́ wọ̀nyí wọ inú òṣù tí a fi pamọ́. Ṣàtúnṣe rẹ kọ́kọ́.",
    "Waɗannan kwanaki sun haɗu da hailar da aka ajiye. Gyara wannan bayanin tukuna.",
    "Ụbọchị ndị a dabara na oge nsọ echekwara. Dezie ndekọ ahụ mbụ.",
  ],
  deleteConfirm: [
    "Delete this record from this browser? This cannot be undone.",
    "Pa àkọsílẹ̀ yìí rẹ́ nínú aṣàwákiri? A kò lè yí padà.",
    "Goge wannan bayanin daga burauza? Ba za a iya dawo da shi ba.",
    "Hichapụ ndekọ a na nchọgharị? Agaghị eweghachi ya.",
  ],
  exportWarning: [
    "The downloaded copy contains private records. Keep it somewhere safe.",
    "Ẹ̀dà tí a gbà sílẹ̀ ní àkọsílẹ̀ àṣírí. Fi sí ibi tó dáa.",
    "Kwafin da aka sauke yana da bayanan sirri. Ajiye shi a wuri mai aminci.",
    "Ihe a budatara nwere ndekọ nzuzo. Debe ya ebe dị nchebe.",
  ],
  noReply: [
    "No reply yet. Try again when connected.",
    "Kò sí èsì síbẹ̀. Gbìyànjú nígbà tí ìsopọ̀ bá wà.",
    "Babu amsa tukuna. Sake gwadawa idan akwai haɗi.",
    "Enweghị nzaghachi ugbu a. Gbalịa ọzọ mgbe ị jikọrọ.",
  ],
  micOff: [
    "Microphone is off. You can type instead.",
    "Gbohungbohun kò ṣiṣẹ́. O lè kọ̀wé dípò rẹ̀.",
    "Makirufo ba ya aiki. Za ki iya rubutawa.",
    "Igwe okwu anaghị arụ ọrụ. Ị nwere ike ide kama ya.",
  ],
  noSpeech: [
    "We couldn’t read the audio. Try again or type.",
    "A kò lè ka ohùn náà. Gbìyànjú tàbí kọ̀wé.",
    "An kasa karanta sauti. Sake gwadawa ko rubuta.",
    "Anyị enweghị ike ịgụ olu. Gbalịa ọzọ ma ọ bụ dee.",
  ],
  sources: ["Sources", "Orísun", "Madogara", "Isi mmalite"],
  carePriority: [
    "Care guidance",
    "Ìtọ́sọ́nà ìtọ́jú",
    "Shawarwarin kulawa",
    "Nduzi nlekọta",
  ],
  privacy: ["Your privacy", "Àṣírí rẹ", "Sirrinki", "Nzuzo gị"],
  manageChats: [
    "Manage conversations",
    "Ṣàkóso ìjíròrò",
    "Sarrafa tattaunawa",
    "Hazie mkparịta ụka",
  ],
  deleteLogs: [
    "Delete period logs",
    "Pa àkọsílẹ̀ òṣù rẹ́",
    "Goge bayanan haila",
    "Hichapụ ndekọ oge nsọ",
  ],
  deleteChats: [
    "Delete conversations",
    "Pa ìjíròrò rẹ́",
    "Goge tattaunawa",
    "Hichapụ mkparịta ụka",
  ],
  estimatedHint: [
    "An estimate based on your saved starts. Cycles can change; this is not a fertility or contraception guarantee.",
    "Àfojúsùn dá lórí ọjọ́ ìbẹ̀rẹ̀ tí o fi pamọ́. Òṣù lè yí padà; kì í ṣe ìdánilójú oyún tàbí ìdènà oyún.",
    "Hasashe bisa farkon hailar da kika ajiye. Zagaye na iya canzawa; ba tabbacin haihuwa ko hana ɗaukar ciki ba.",
    "Atụmatụ dabere na ụbọchị mmalite echekwara. Oge nsọ nwere ike ịgbanwe; ọ bụghị nkwa ọmụmụ ma ọ bụ mgbochi ime.",
  ],
  replyAudio: [
    "Get reply audio",
    "Gba ohùn èsì",
    "Samu sautin amsa",
    "Nweta olu nzaghachi",
  ],
  sharePreview: [
    "This message may contain private health information. Share only when you choose.",
    "Ọ̀rọ̀ yìí lè ní àlàyé ìlera àṣírí. Pín bí o bá fẹ́ nìkan.",
    "Wannan saƙon na iya ƙunsar bayanan lafiyar sirri. Raba shi idan kin zaɓa.",
    "Ozi a nwere ike ịnwe ozi ahụike nzuzo. Kekọrịta naanị mgbe ị họọrọ.",
  ],
  copyDone: ["Copied", "A ti da kọ", "An kwafi", "E detuola"],
  letsTalk: [
    "Let’s talk.",
    "Jẹ́ ká sọ̀rọ̀.",
    "Mu yi magana.",
    "Ka anyị kwuo okwu.",
  ],
  shortVoice: [
    "Short voice notes. Simple replies.",
    "Ohùn kúkúrú. Èsì tó rọrùn.",
    "Gajerun saƙonnin murya. Amsoshi masu sauƙi.",
    "Obere ozi olu. Nzaghachi dị mfe.",
  ],
  noConversations: [
    "No conversations yet",
    "Kò sí ìjíròrò síbẹ̀",
    "Babu tattaunawa tukuna",
    "Enweghị mkparịta ụka ugbu a",
  ],
  moreOptions: [
    "More options",
    "Àṣàyàn sí i",
    "Ƙarin zaɓuɓɓuka",
    "Nhọrọ ndị ọzọ",
  ],
  addEnd: [
    "Add an end date",
    "Fi ọjọ́ ìparí kún un",
    "Ƙara ranar ƙarewa",
    "Tinye ụbọchị njedebe",
  ],
  privacyDetails: [
    "Storage & processing details",
    "Àlàyé ìpamọ́ àti ṣíṣe",
    "Bayanin ajiya da sarrafawa",
    "Nkọwa nchekwa na nhazi",
  ],
  draftSaved: [
    "Unsent draft",
    "Àkọ́kọ́ tí a kò ránṣẹ́",
    "Daftarin da ba a aika ba",
    "Ihe e dere ezipụghị",
  ],
  saveDraft: [
    "Keep draft",
    "Fi àkọ́kọ́ pamọ́",
    "Ajiye daftari",
    "Chekwaa ihe e dere",
  ],
  cancelReply: ["Cancel reply", "Fagilé èsì", "Soke amsa", "Kagbuo nzaghachi"],
  processingVoice: [
    "Voice & AI processing",
    "Ṣíṣe ohùn àti AI",
    "Sarrafawar murya da AI",
    "Nhazi olu na AI",
  ],
  moreCare: [
    "Seek in-person care for severe, unusual or worrying symptoms. ÌleraHer does not provide emergency care.",
    "Wá ìtọ́jú ní ojúkojú fún àmì tó le, àjèjì tàbí tó ń dà ọ́ láàmú. ÌleraHer kì í pèsè ìtọ́jú pàjáwìrì.",
    "Nemi kulawa a asibiti idan alamomi sun tsananta ko suna damunki. ÌleraHer ba ya bayar da kulawar gaggawa.",
    "Chọọ nlekọta n'ihu onye ọrụ ahụike maka mgbaàmà siri ike ma ọ bụ na-enye nsogbu. ÌleraHer anaghị enye nlekọta mberede.",
  ],
  messageLimit: [
    "Keep your question within 1,200 characters.",
    "Jẹ́ kí ìbéèrè rẹ má kọjá lẹ́tà 1,200.",
    "Tambayarki kada ta wuce haruffa 1,200.",
    "Ajụjụ gị agaghị agafe mkpụrụedemede 1,200.",
  ],
  accountStorage: [
    "Account details and submitted feedback are stored on our server. Browser records are not account-specific. Anyone using this browser can access them after signing in.",
    "A ń tọ́jú àlàyé àkọọ́lẹ̀ àti èrò tí a fi ránṣẹ́ sí wa lórí ẹ̀rọ ìpamọ́ wa. Àkọsílẹ̀ aṣàwákiri kò jẹ́ ti àkọọ́lẹ̀ kan ṣoṣo. Ẹnikẹ́ni tó ń lo aṣàwákiri yìí lè rí wọn lẹ́yìn tí wọ́n wọlé.",
    "Ana adana bayanan asusu da ra’ayin da aka aika a sabarmu. Bayanan burauza ba na asusu guda ba ne. Duk wanda ke amfani da wannan burauza zai iya ganin su bayan shiga.",
    "A na-echekwa nkọwa akaụntụ na nzaghachi ezigara na sava anyị. Ndekọ ihe nchọgharị abụghị nke otu akaụntụ. Onye ọ bụla na-eji ihe nchọgharị a nwere ike ịhụ ha mgbe ọ banyere.",
  ],
  callCharges: [
    "Network and international call charges may apply. Calls require recording consent; ÌleraHer is not an emergency service.",
    "Owo ìpè nẹ́tíwọ́ọ̀kì àti ti òkè òkun lè wà. Ìpè nílò ìyọ̀ǹda fún gbígbàsílẹ̀; ÌleraHer kì í ṣe iṣẹ́ pàjáwìrì.",
    "Ana iya cajin kira na hanyar sadarwa da na ƙasashen waje. Kira yana buƙatar izinin rikodi; ÌleraHer ba sabis na gaggawa ba ne.",
    "Enwere ike ịnwe ụgwọ netwọkụ na oku mba ofesi. Oku chọrọ nkwenye ndekọ; ÌleraHer abụghị ọrụ mberede.",
  ],
  storageUnavailable: [
    "Saved conversations could not be opened. New messages remain in this tab until storage is available.",
    "A kò lè ṣí ìjíròrò tí a tọ́jú. Àwọn ọ̀rọ̀ tuntun wà ní ojú ìwé yìí títí ìpamọ́ yóò fi wà.",
    "Ba a iya buɗe tattaunawar da aka adana ba. Sabbin saƙonni za su kasance a wannan shafin har sai an samu wurin ajiya.",
    "Enweghị ike imeghe mkparịta ụka echekwara. Ozi ọhụrụ ga-anọ na taabụ a ruo mgbe nchekwa dị.",
  ],
  microphoneUnavailable: [
    "Microphone access is unavailable. Check microphone permissions and try again.",
    "A kò lè lo gbohungbohun. Ṣàyẹ̀wò ìyọ̀ǹda gbohungbohun kí o tún gbìyànjú.",
    "Ba a iya samun damar makirufo ba. Duba izininsa kuma a sake gwadawa.",
    "Enweghị ike iji igwe okwu. Lelee ikike igwe okwu wee nwaa ọzọ.",
  ],
  welcomeBack: ["Welcome back", "Ẹ káàbọ̀ padà", "Barka da dawowa", "Nnọọ ọzọ"],
  signInHint: [
    "Enter the phone number and password you used when creating your account.",
    "Tẹ nọ́ńbà fóònù àti ọ̀rọ̀ ìgbaniwọlé tí o lò nígbà tí o ṣẹ̀dá àkọọ́lẹ̀ rẹ.",
    "Shigar da lambar waya da kalmar sirri da kika yi amfani da su lokacin ƙirƙirar asusunki.",
    "Tinye nọmba ekwentị na okwuntughe i ji mepụta akaụntụ gị.",
  ],
  createHint: [
    "Create your private account with a phone number and password.",
    "Ṣẹ̀dá àkọọ́lẹ̀ àṣírí rẹ pẹ̀lú nọ́ńbà fóònù àti ọ̀rọ̀ ìgbaniwọlé.",
    "Ƙirƙiri asusunki na sirri da lambar waya da kalmar sirri.",
    "Mepụta akaụntụ nzuzo gị na nọmba ekwentị na okwuntughe.",
  ],
  alreadyAccount: [
    "Already have an account?",
    "Ṣé o ti ní àkọọ́lẹ̀?",
    "Kina da asusu?",
    "Ị nweela akaụntụ?",
  ],
  newHere: [
    "New to ÌleraHer?",
    "Ṣé o jẹ́ tuntun sí ÌleraHer?",
    "Sabuwar mai amfani da ÌleraHer?",
    "Ị bụ onye ọhụrụ na ÌleraHer?",
  ],
  passwordMismatch: [
    "Passwords do not match.",
    "Àwọn ọ̀rọ̀ ìgbaniwọlé kò bá ara wọn mu.",
    "Kalmomin sirri ba su daidaita ba.",
    "Okwuntughe adabaghị.",
  ],
  unsentDraft: [
    "Unsent draft",
    "Ọ̀rọ̀ tí a kò tíì ránṣẹ́",
    "Saƙon da ba a aika ba",
    "Ozi ezigarabeghị",
  ],
  recordingUnavailable: [
    "Recording is unavailable. Check microphone permissions and try again.",
    "Gbígbàsílẹ̀ kò wà. Ṣàyẹ̀wò ìyọ̀ǹda gbohungbohun kí o tún gbìyànjú.",
    "Ba a iya yin rikodi ba. Duba izinin makirufo kuma a sake gwadawa.",
    "Enweghị ike idekọ. Lelee ikike igwe okwu wee nwaa ọzọ.",
  ],
  phoneSetup: ["Calling PIN & replies", "PIN ìpè àti èsì", "PIN na kira da amsoshi", "PIN oku na nzaghachi"],
  phoneCallingPin: ["Six digit calling PIN", "PIN ìpè olónọ́mbà mẹ́fà", "PIN na kira mai lambobi shida", "PIN oku nwere ọnụọgụ isii"],
  phoneConfirmPin: ["Confirm calling PIN", "Jẹ́rìí PIN ìpè", "Tabbatar da PIN na kira", "Kwenye PIN oku"],
  phonePinMismatch: ["Calling PINs do not match.", "Àwọn PIN ìpè kò bá ara wọn mu.", "PIN na kira ba su daidaita ba.", "PIN oku adabaghị."],
  phoneSavePin: ["Save calling PIN", "Fi PIN ìpè pamọ́", "Ajiye PIN na kira", "Chekwaa PIN oku"],
  phoneRegistered: ["Your registered number", "Nọ́mbà tí o forúkọsílẹ̀", "Lambar da kika yi rajista", "Nọmba ị debanyere"],
  phoneSaveReplies: ["Save played call replies for 30 days", "Fi èsì ìpè tí a gbọ́ pamọ́ fún ọjọ́ 30", "Ajiye amsoshin kira da aka saurara na kwanaki 30", "Chekwaa nzaghachi oku e gere ruo ụbọchị 30"],
  phonePrivacyHint: ["Calls process short voice recordings. Saving replies is optional. Your browser period logs are not available by phone.", "Ìpè ń ṣe àkọsílẹ̀ ohùn kúkúrú. Fífipamọ́ èsì jẹ́ àṣàyàn. Àkọsílẹ̀ òṣù aṣàwákiri kò wà lórí ìpè.", "Ana sarrafa gajerun rikodin murya a kira. Ajiye amsoshi zaɓi ne. Bayanan haila na burauza ba sa samuwa ta waya.", "Oku na-ahazi obere ndekọ olu. Ịchekwa nzaghachi bụ nhọrọ. Ndekọ oge nsọ nchọgharị adịghị na oku."],
  phoneRemove: ["Disable calling & delete replies", "Dá ìpè dúró kí o pa èsì rẹ́", "Kashe kira da goge amsoshi", "Gbanyụọ oku ma hichapụ nzaghachi"],
  phonePinChangeHint: ["Changing your PIN ends active calls. Turning off saved replies deletes previous call replies.", "Yíyí PIN rẹ padà ń parí ìpè tó ń lọ. Dídá fífi èsì pamọ́ dúró ń pa èsì àtijọ́ rẹ́.", "Canza PIN yana ƙare kiran da ake yi. Kashe ajiyar amsoshi yana goge tsoffin amsoshin kira.", "Ịgbanwe PIN na-akwụsị oku na-aga. Ịkwụsị ichekwa nzaghachi na-ehichapụ nzaghachi ochie."],
  phoneReplies: ["Call replies", "Èsì ìpè", "Amsoshin kira", "Nzaghachi oku"],
  phoneNoReplies: ["No saved call replies yet.", "Kò sí èsì ìpè tí a fi pamọ́ síbẹ̀.", "Babu amsoshin kira da aka ajiye tukuna.", "Enweghị nzaghachi oku echekwara ugbu a."],
  phonePilotPending: ["The phone pilot is being connected. You can prepare your calling PIN now.", "A ń so ìpè ìdánwò pọ̀. O lè ṣètò PIN ìpè rẹ báyìí.", "Ana haɗa gwajin kira. Za ki iya saita PIN na kira yanzu.", "A na-ejikọta nnwale oku. Ị nwere ike ịkwadebe PIN oku ugbu a."],
  phoneCallHint: ["Call, choose a language, and enter your calling PIN using the keypad.", "Pè, yan èdè, kí o tẹ PIN ìpè rẹ.", "Kira, zaɓi harshe, sannan shigar da PIN na kira.", "Kpọọ oku, họrọ asụsụ, ma tinye PIN oku."],
  phoneSaved: ["Calling PIN saved.", "A ti fi PIN ìpè pamọ́.", "An ajiye PIN na kira.", "E chekwara PIN oku."],
  phoneRemoved: ["Calling disabled and saved call replies deleted.", "A ti dá ìpè dúró a sì pa èsì ìpè rẹ́.", "An kashe kira kuma an goge amsoshin kira.", "E gbanyụọla oku ma hichapụ nzaghachi oku."],
  phoneAccountError: ["Calling settings could not be updated. Try again when connected.", "A kò lè ṣàtúnṣe ètò ìpè. Gbìyànjú nígbà tí ìsopọ̀ bá wà.", "An kasa sabunta saitunan kira. Sake gwadawa idan akwai haɗi.", "Enweghị ike imelite ntọala oku. Gbalịa mgbe ị jikọrọ."],
  phoneReviewed: ["Reviewed guidance", "Ìtọ́sọ́nà tí a ṣàyẹ̀wò", "Shawarar da aka duba", "Nduzi a nyochara"],
} as const;
export type UIKey = keyof typeof rows;
const index: Record<IlaraLanguage, number> = {
  "en-NG": 0,
  yo: 1,
  ha: 2,
  ig: 3,
};
export function uiText(key: UIKey, language: IlaraLanguage) {
  return rows[key][index[language]];
}
export function useUI() {
  const { language, setLanguage } = useLanguage();
  return {
    language,
    setLanguage,
    t: (key: UIKey) => uiText(key, language),
    locale: language === "en-NG" ? "en-NG" : language + "-NG",
  };
}

export const UI_KEYS = Object.keys(rows) as UIKey[];
const symptomKeys: Record<string, UIKey> = {
  Cramps: "cramps",
  Tired: "tired",
  "Tender breasts": "tender",
  Headache: "headache",
};
export function symptomText(value: string, t: (key: UIKey) => string) {
  return symptomKeys[value] ? t(symptomKeys[value]) : value;
}
